default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

  # Important configs for cloud9, change password value
  # to what you entered in the previous psql step.
  template: template0
  username: ubuntu
  password: password

development:
  <<: *default
  database: birthday

test:
  <<: *default
  database: birthday

production:
  <<: *default
  database: birhtday
  username: birthday
  password: <%= ENV['YOUR_APP_NAME_DATABASE_PASSWORD'] %>
